### ISSUE TITLE
Cannot import name 'bitmex'

### ISSUE THREAD

**Issue by caressgents** [judgelight/Bitmex_market_maker#1]
Getting the following error when trying to run 'python custom_strategy_V4.py' 

`Traceback (most recent call last):
  File "custom_strategy_V4.py", line 12, in <module>
    from market_maker.market_maker import OrderManager, XBt_to_XBT
  File "/home/nateflanders/Bitmex_market_maker/market_maker.py", line 11, in <module>
    from market_maker import bitmex
`

Thanks in advance

**Comment by caressgents** [comment]
@judgelight

**Comment by judgelight** [comment]
Please change the dir "/home/nateflanders/Bitmex_market_maker" to "/home/nateflanders/market_maker".
The original dir name is 'market_maker'.

**Comment by caressgents** [comment]
```
python custom_strategy_V4.py
Traceback (most recent call last):
  File "custom_strategy_V4.py", line 12, in <module>
    from market_maker.market_maker import OrderManager, XBt_to_XBT
  File "/home/nateflanders/market_maker/market_maker.py", line 11, in <module>
    from market_maker import bitmex
ImportError: cannot import name 'bitmex'
```
Still getting the same error.
