### ISSUE TITLE
having directory issues apparently

### ISSUE THREAD

**Issue by caressgents** [judgelight/Bitmex_market_maker#2]
@judgelight 

Now getting the following, and it's got me stumped.

```
python3 custom_strategy_V4.py
Traceback (most recent call last):
  File "custom_strategy_V4.py", line 12, in <module>
    from market_maker.market_maker import OrderManager, XBt_to_XBT
  File "/home/nateflanders/judgelight/market_maker/market_maker.py", line 11, in <module>
    from market_maker import bitmex
  File "/home/nateflanders/judgelight/market_maker/bitmex.py", line 12, in <module>
    from market_maker.ws.ws_thread import BitMEXWebsocket
  File "/home/nateflanders/judgelight/market_maker/ws/ws_thread.py", line 16, in <module>
    from telegram_msg import tg_send_message, tg_send_important_message
ModuleNotFoundError: No module named 'telegram_msg'
```

**Comment by judgelight** [comment]
That's for telegram notice. You need build your own telegram bot to use it.
If you don't have it. Just delete it
